### ISSUE TITLE
Escopo de submissão do fomulário não está funcionando

### ISSUE THREAD

**Issue by stellaoliveirabertt** [stellaoliveirabertt/PeoplePro#20]
- [ ] Erro ao submeter o cadastro do colaborador

![Image](https://github.com/stellaoliveirabertt/PeoplePro/assets/19766421/b9fd2dff-32ea-4d2c-9875-91af5ebaecd3)

**Comment by gloinho** [comment]
Isso aqui é por conta daquele b.o do `async await`
Retirando o `"babel-plugin-transform-async-to-generator": "^6.24.1"`  volta a funcionar direitinho.
